<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Destination;
use App\Models\Tour;
use App\Models\TourCategory;
use Illuminate\Support\Str;

class TourSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tours = [
            [
                'destination' => 'Dubai',
                'category' => 'Adventure',
                'title' => 'Dubai Desert Safari & City Highlights',
                'tour_code' => 'TB-DXB-001',
                'tagline' => 'Skyline, sand dunes and luxury shopping',
                'short_description' => 'Experience Dubai\'s iconic skyscrapers, thrilling desert safari and world-class attractions on an unforgettable holiday.',
                'description' => '<p>Discover the dazzling city of Dubai with guided city tours, a thrilling desert safari with dune bashing, camel riding, BBQ dinner and visits to Burj Khalifa, Dubai Mall and the historic Al Fahidi district.</p>',
                'featured_image' => 'images/destinations/dubai.jpg',
                'price' => 185000,
                'discount_price' => 165000,
                'duration_days' => 5,
                'duration_nights' => 4,
                'max_people' => 15,
                'min_age' => 5,
                'rating' => 4.8,
                'reviews_count' => 124,
                'featured' => true,
                'popular' => true,
                'sort_order' => 1,
            ],
            [
                'destination' => 'Bali',
                'category' => 'Honeymoon',
                'title' => 'Bali Honeymoon Special',
                'tour_code' => 'TB-BAL-002',
                'tagline' => 'Island of Gods romantic escape',
                'short_description' => 'A dreamy honeymoon in Bali with private villas, romantic dinners, temples and pristine beaches.',
                'description' => '<p>Celebrate your love in Bali with luxurious private pool villas, romantic sunset dinners, visits to the iconic temples, Ubud rice terraces and relaxing beach time in Nusa Dua.</p>',
                'featured_image' => 'images/destinations/bali.jpg',
                'price' => 165000,
                'discount_price' => 148000,
                'duration_days' => 6,
                'duration_nights' => 5,
                'max_people' => 10,
                'min_age' => 18,
                'rating' => 4.9,
                'reviews_count' => 98,
                'featured' => true,
                'popular' => true,
                'sort_order' => 2,
            ],
            [
                'destination' => 'Paris',
                'category' => 'Luxury',
                'title' => 'Paris Luxury & Romance Tour',
                'tour_code' => 'TB-PAR-003',
                'tagline' => 'The city of love in style',
                'short_description' => 'Indulge in a luxurious Parisian experience with the Eiffel Tower, Louvre and fine dining.',
                'description' => '<p>Enjoy a premium Paris escape featuring skip-the-line Eiffel Tower visits, the Louvre Museum, Seine river cruise, luxury accommodation and gourmet French dining.</p>',
                'featured_image' => 'images/destinations/paris.jpg',
                'price' => 285000,
                'discount_price' => null,
                'duration_days' => 7,
                'duration_nights' => 6,
                'max_people' => 12,
                'min_age' => 12,
                'rating' => 4.7,
                'reviews_count' => 76,
                'featured' => true,
                'popular' => false,
                'sort_order' => 3,
            ],
            [
                'destination' => 'Istanbul',
                'category' => 'Cultural',
                'title' => 'Istanbul Heritage & Bosphorus Tour',
                'tour_code' => 'TB-IST-004',
                'tagline' => 'Where East meets West',
                'short_description' => 'Explore the rich history of Istanbul with mosques, palaces, bazaars and a Bosphorus cruise.',
                'description' => '<p>Journey through Istanbul\'s incredible history visiting Hagia Sophia, Blue Mosque, Topkapi Palace, the Grand Bazaar and enjoying a relaxing Bosphorus cruise.</p>',
                'featured_image' => 'images/destinations/istanbul.jpg',
                'price' => 155000,
                'discount_price' => 139000,
                'duration_days' => 5,
                'duration_nights' => 4,
                'max_people' => 20,
                'min_age' => 5,
                'rating' => 4.6,
                'reviews_count' => 152,
                'featured' => true,
                'popular' => true,
                'sort_order' => 4,
            ],
            [
                'destination' => 'Bangkok',
                'category' => 'Group Tours',
                'title' => 'Bangkok Adventure Group Tour',
                'tour_code' => 'TB-BKK-005',
                'tagline' => 'Temples, street food and vibrant nightlife',
                'short_description' => 'An exciting group tour through Bangkok\'s temples, floating markets, shopping and nightlife.',
                'description' => '<p>Explore Bangkok with a fun group, visiting the Grand Palace, floating markets, vibrant night markets and sampling the city\'s legendary street food.</p>',
                'featured_image' => 'images/destinations/bangkok.jpg',
                'price' => 145000,
                'discount_price' => null,
                'duration_days' => 4,
                'duration_nights' => 3,
                'max_people' => 25,
                'min_age' => 5,
                'rating' => 4.5,
                'reviews_count' => 88,
                'featured' => true,
                'popular' => false,
                'sort_order' => 5,
            ],
            [
                'destination' => 'Maldives',
                'category' => 'Beach',
                'title' => 'Maldives Beach Paradise',
                'tour_code' => 'TB-MDV-006',
                'tagline' => 'Crystal clear waters and overwater villas',
                'short_description' => 'A tropical beach escape in the Maldives with overwater villas and snorkeling adventures.',
                'description' => '<p>Escape to the Maldives for a stay in luxurious overwater villas, snorkeling in crystal-clear lagoons and relaxing on white-sand beaches.</p>',
                'featured_image' => 'images/destinations/maldives.jpg',
                'price' => 325000,
                'discount_price' => 295000,
                'duration_days' => 6,
                'duration_nights' => 5,
                'max_people' => 8,
                'min_age' => 5,
                'rating' => 4.9,
                'reviews_count' => 143,
                'featured' => true,
                'popular' => true,
                'sort_order' => 6,
            ],
            [
                'destination' => 'Zurich',
                'category' => 'Luxury',
                'title' => 'Zurich Swiss Alps Escape',
                'tour_code' => 'TB-ZRH-007',
                'tagline' => 'Alpine lakes and snow-capped peaks',
                'short_description' => 'A premium Swiss holiday featuring Zurich, scenic train rides and Alpine views.',
                'description' => '<p>Discover Switzerland\'s beauty with a visit to Zurich lake city, scenic mountain train journeys and breathtaking snow-capped Alpine views.</p>',
                'featured_image' => 'images/destinations/zurich.jpg',
                'price' => 310000,
                'discount_price' => null,
                'duration_days' => 7,
                'duration_nights' => 6,
                'max_people' => 12,
                'min_age' => 12,
                'rating' => 4.8,
                'reviews_count' => 64,
                'featured' => false,
                'popular' => false,
                'sort_order' => 7,
            ],
            [
                'destination' => 'Hunza',
                'category' => 'Adventure',
                'title' => 'Hunza Valley Adventure Tour',
                'tour_code' => 'TB-HNZ-008',
                'tagline' => 'Heaven on Earth',
                'short_description' => 'Explore the breathtaking Hunza Valley with Attabad Lake and the majestic Karakoram mountains.',
                'description' => '<p>Trek through the stunning Hunza Valley visiting Attabad Lake, Passu Cones, Eagle Nest viewpoint and the historic Karimabad bazaar.</p>',
                'featured_image' => 'images/destinations/hunza.jpg',
                'price' => 35000,
                'discount_price' => 32000,
                'duration_days' => 6,
                'duration_nights' => 5,
                'max_people' => 18,
                'min_age' => 8,
                'rating' => 4.7,
                'reviews_count' => 210,
                'featured' => true,
                'popular' => true,
                'sort_order' => 8,
            ],
            [
                'destination' => 'Skardu',
                'category' => 'Adventure',
                'title' => 'Skardu Lakes & Mountains Tour',
                'tour_code' => 'TB-SKD-009',
                'tagline' => 'Land of majestic mountains and serene lakes',
                'short_description' => 'Discover Skardu\'s Shangrila Resort, Kachura Lakes and the gateway to K2.',
                'description' => '<p>Explore the breathtaking landscape of Skardu including Shangrila Resort, Upper Kachura Lake, Satpara Lake and the vast Deosai National Park plains.</p>',
                'featured_image' => 'images/destinations/skardu.jpg',
                'price' => 45000,
                'discount_price' => 40000,
                'duration_days' => 7,
                'duration_nights' => 6,
                'max_people' => 16,
                'min_age' => 8,
                'rating' => 4.6,
                'reviews_count' => 175,
                'featured' => true,
                'popular' => true,
                'sort_order' => 9,
            ],
            [
                'destination' => 'Kuala Lumpur',
                'category' => 'Family',
                'title' => 'Kuala Lumpur Family Fun Tour',
                'tour_code' => 'TB-KUL-010',
                'tagline' => 'Twin Towers and family adventures',
                'short_description' => 'A fun-filled family tour of Kuala Lumpur with the Petronas Towers and Genting Highlands.',
                'description' => '<p>Enjoy a family holiday in Kuala Lumpur visiting the Petronas Twin Towers, Genting Highlands theme parks and exploring the city\'s shopping and food scene.</p>',
                'featured_image' => 'images/destinations/kuala-lumpur.jpg',
                'price' => 135000,
                'discount_price' => 120000,
                'duration_days' => 5,
                'duration_nights' => 4,
                'max_people' => 20,
                'min_age' => 3,
                'rating' => 4.5,
                'reviews_count' => 92,
                'featured' => true,
                'popular' => true,
                'sort_order' => 10,
            ],
        ];

        foreach ($tours as $index => $item) {
            $destination = Destination::where('name', $item['destination'])->first();
            $category = TourCategory::where('name', $item['category'])->first();

            if (!$destination || !$category) {
                continue;
            }

            Tour::updateOrCreate(
                ['slug' => Str::slug($item['title'])],
                [
                    'destination_id' => $destination->id,
                    'tour_category_id' => $category->id,
                    'title' => $item['title'],
                    'slug' => Str::slug($item['title']),
                    'tour_code' => $item['tour_code'],
                    'tagline' => $item['tagline'],
                    'short_description' => $item['short_description'],
                    'description' => $item['description'],
                    'featured_image' => $item['featured_image'],
                    'price' => $item['price'],
                    'discount_price' => $item['discount_price'],
                    'duration_days' => $item['duration_days'],
                    'duration_nights' => $item['duration_nights'],
                    'max_people' => $item['max_people'],
                    'min_age' => $item['min_age'],
                    'rating' => $item['rating'],
                    'reviews_count' => $item['reviews_count'],
                    'featured' => $item['featured'],
                    'popular' => $item['popular'],
                    'status' => true,
                    'sort_order' => $item['sort_order'],
                    'meta_title' => $item['title'].' Tour Package',
                    'meta_description' => 'Book the '.$item['title'].' with flights, hotels and guided tours at the best price.',
                ]
            );
        }
    }
}
